"""Add CompanyType Enum to company

Revision ID: 697f46f9a905
Revises: 998c60089b82
Create Date: 2025-10-27 14:31:20.445224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697f46f9a905'
down_revision: Union[str, Sequence[str], None] = '998c60089b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('todo_user_id_fkey'), 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('todo_user_id_fkey'), 'todo', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
