"""renamed todos to todo

Revision ID: 998c60089b82
Revises: b084aab31149
Create Date: 2025-10-23 14:25:23.896922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998c60089b82'
down_revision: Union[str, Sequence[str], None] = 'b084aab31149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('todos', 'todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('todo', 'todos')
    # ### end Alembic commands ###
