"""Add full_name bio profile to user

Revision ID: b688ad9a6411
Revises: 34d17ef633a7
Create Date: 2025-10-22 15:35:30.465282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b688ad9a6411'
down_revision: Union[str, Sequence[str], None] = '34d17ef633a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
