"""renamed type to company_type in Company model

Revision ID: b6ea24863180
Revises: e1389d54a4b4
Create Date: 2025-10-15 16:56:05.452033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ea24863180'
down_revision: Union[str, Sequence[str], None] = 'e1389d54a4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_type', sa.String(), nullable=True))
    op.drop_column('company', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('company', 'company_type')
    # ### end Alembic commands ###
