"""add type column to company

Revision ID: e1389d54a4b4
Revises: 25d8f59a1dde
Create Date: 2025-10-13 14:20:56.229293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1389d54a4b4'
down_revision: Union[str, Sequence[str], None] = '25d8f59a1dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'type')
    # ### end Alembic commands ###
